name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Print
      run: |
        cd print/
        cargo build --verbose
        
    - name: Test Print
      run: |
        cd print/
        cargo test --verbose
