name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build print
      run: |
        cd print/
        cargo build --verbose
        
    - name: Test print
      run: |
        cd print/
        cargo test --verbose

    - name: Build datatypes
      run: |
        cd datatypes/
        cargo build --verbose
    
    - name: Test datatypes
      run: |
        cd datatypes/
        cargo test --verbose

    - name: Build variables
      run: |
        cd datatypes/
        cargo build --verbose
    
    - name: Test veriables
      run: |
        cd datatypes/
        cargo test --verbose
    
    - name: Build consts
      run: |
        cd consts/
        cargo build --verbose
      
    - name: Test consts
      run: |
        cd consts/
        cargo test --verbose

    - name: Build strings
      run: |
        cd strings/
        cargo build --verbose 
    
    - name: Test strings
      run: |
        cd strings/
        cargo test --verbose
    
    - name: Build loops
      run: |
        cd loops/
        cargo build --verbose
    
    - name: Test loops
      run: |
        cd loops/
        cargo test --verbose